global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gujpol-api"
    static_configs:
      - targets: ["app-api:8000"]
    metrics_path: /metrics

  - job_name: "model-server"
    static_configs:
      - targets: ["model-server:8080"]
    metrics_path: /metrics

  - job_name: "postgres"
    static_configs:
      - targets: ["db-postgres:5432"]

  - job_name: "redis"
    static_configs:
      - targets: ["cache-redis:6379"]
